c_compiler:
  - clang     # [unix]
c_compiler_version:
  - 21        # [linux]
  - 19        # [osx]
cxx_compiler:
  - clangxx   # [unix]
cxx_compiler_version:
  - 21        # [linux]
  - 19        # [osx]
